TO_ABB = {
    "probability of edge": "PE",
    "in-degree": "ID",
    "out-degree": "OD",
    "number of nodes": "NN",
    "number of chains": "NC",
    "main sequence length": "MSL",
    "number of sub sequences": "NSS",
    "number of source nodes": "NEN",
    "number of exit nodes": "NEX",
    "communication time": "CT",
    "execution time": "ET",
    "ccr": "CCR",
    "ratio of deadline to critical path": "RDC",
    "offset": "OS",
    "period": "P",
    "source node period": "ENP",
    "exit node period": "EXP",
    "total utilization": "TU",
    "maximum utilization": "MU",
}
