TO_ABB = {
    'probability of edge': 'PE',
    'PNG': 'PNG',
    'SVG': 'SVG',
    'PDF': 'PDF',
    'EPS': 'EPS',
    'draw legend': 'DL',
    'YAML': 'YAML',
    'JSON': 'JSON',
    'DOT': 'DOT',
    'XML': 'XML',
    'figure': 'FIG',
    'dag': 'dag',
    'seed': 'seed',
    'offset': 'OS',
    'communication time': 'CT',
    'end-to-end deadline': 'EED',
    'additional properties': 'AP',
    'node properties': 'NP',
    'edge properties': 'EP',
    'multi-period': 'MP',
    'properties': 'PP',
    'graph structure': 'GS',
    'generation method': 'GM',
    'total utilization': 'TU',
    'output formats': 'OF',
    'naming of combination directory': 'NCD',
    'number of dags': 'NG',
    'number of nodes': 'NN',
    'number of entry nodes': 'NEN',
    'in-degree': 'ID',
    'out-degree': 'OD',
    'execution time': 'ET',
    'max number of same-depth nodes': 'MNSD',
    'force merge to exit nodes': 'FME',
    'number of exit nodes': 'NEX',
    'use end-to-end deadline': 'UED',
    'ratio of deadline to critical path': 'RDC',
    'ratio of deadlines to max period': 'RDP',
    'use communication time': 'UCT',
    'use multi-period': 'UMP',
    'periodic type': 'PT',
    'period': 'P',
    'entry node period': 'ENP',
    'exit node period': 'EXP',
    'max ratio of execution time to period': 'MREP',
    'descendants have larger period': 'DLP',
    # chain
    'number of chains': 'NC',
    'chain length': 'CL',
    'chain width': 'CW',
    'vertically link chains': 'VLC',
    'max level of vertical links': 'MLV',
    'merge chains': 'MGC',
    'middle of chain': 'MDC',
    'exit node': 'EXN',
    'head of chain': 'HDC'
}

TO_ORI = {
    'PE': 'probability of edge',
    'PNG': 'png',
    'SVG': 'svg',
    'PDF': 'pdf',
    'EPS': 'eps',
    'DL': 'draw legend',
    'YAML': 'yaml',
    'JSON': 'json',
    'DOT': 'dot',
    'XML': 'xml',
    'FIG': 'figure',
    'DAG': 'dag',
    'seed': 'seed',
    'OS': 'offset',
    'CT': 'communication time',
    'EED': 'end-to-end deadline',
    'AP': 'additional properties',
    'NP': 'node properties',
    'EP': 'edge properties',
    'MP': 'multi-period',
    'PP': 'properties',
    'GS': 'graph structure',
    'GM': 'generation method',
    'TU': 'total utilization',
    'OF': 'output formats',
    'NCD': 'naming of combination directory',
    'NG': 'number of dags',
    'NN': 'number of nodes',
    'NEN': 'number of entry nodes',
    'ID': 'in-degree',
    'OD': 'out-degree',
    'ET': 'execution time',
    'MNSD': 'max number of same-depth nodes',
    'FME': 'force merge to exit nodes',
    'NEX': 'number of exit nodes',
    'UED': 'use end-to-end deadline',
    'RDC': 'ratio of deadline to critical path',
    'RDP': 'ratio of deadlines to max period',
    'UCT': 'use communication time',
    'UMP': 'use multi-period',
    'PT': 'periodic type',
    'P': 'period',
    'ENP': 'entry node period',
    'EXP': 'exit node period',
    'MREP': 'max ratio of execution time to period',
    'DLP': 'descendants have larger period',
    # chain
    'NC': 'number of chains',
    'CL': 'chain length',
    'CW': 'chain width',
    'VLC': 'vertically link chains',
    'MLV': 'max level of vertical links',
    'MGC': 'merge chains',
    'MDC': 'middle of chain',
    'EXN': 'exit node',
    'HDC': 'head of chain'
}
