TO_ABB = {
    'properties': 'PP',
    'graph structure': 'GS',
    'generation method': 'GM',
    'total utilization': 'TU',
    'output formats': 'OF',
    'naming of combination directory': 'NCD',
    'number of dags': 'NG',
    'number of nodes': 'NN',
    'number of entry nodes': 'NEN',
    'in-degree': 'ID',
    'out-degree': 'OD',
    'execution time': 'ET',
    'max number of same-depth nodes': 'MNSD',
    'force merge to exit nodes': 'FME',
    'number of exit nodes': 'NEX',
    'use end-to-end deadline': 'UED',
    'ratio of deadlines to critical path length': 'RDC',
    'ratio of deadlines to max period': 'RDP',
    'use communication time': 'UCT',
    'use multi-period': 'UMP',
    'periodic type': 'PT',
    'period': 'P',
    'entry node periods': 'ENP',
    'exit node periods': 'EXP',
    'max ratio of execution time to period': 'MREP',
    'descendants have larger period': 'DLP',
    # chain
    'number of chains': 'NC',
    'chain length': 'CL',
    'chain width': 'CW',
    'vertically link chains': 'VLC',
    'max level of vertical links': 'MLV',
    'merge chains': 'MGC',
    'middle of chain': 'MDC',
    'exit node': 'EXN',
    'head of chain': 'HDC'
}

TO_ORI = {
    'PP': 'properties',
    'GS': 'graph structure',
    'GM': 'generation method',
    'TU': 'total utilization',
    'OF': 'output formats',
    'NCD': 'naming of combination directory',
    'NG': 'number of dags',
    'NN': 'number of nodes',
    'NEN': 'number of entry nodes',
    'ID': 'in-degree',
    'OD': 'out-degree',
    'ET': 'execution time',
    'MNSD': 'max number of same-depth nodes',
    'FME': 'force merge to exit nodes',
    'NEX': 'number of exit nodes',
    'UED': 'use end-to-end deadline',
    'RDC': 'ratio of deadlines to critical path length',
    'RDP': 'ratio of deadlines to max period',
    'UCT': 'use communication time',
    'UMP': 'use multi-period',
    'PT': 'periodic type',
    'P': 'period',
    'ENP': 'entry node periods',
    'EXP': 'exit node periods',
    'MREP': 'max ratio of execution time to period',
    'DLP': 'descendants have larger period',
    # chain
    'NC': 'number of chains',
    'CL': 'chain length',
    'CW': 'chain width',
    'VLC': 'vertically link chains',
    'MLV': 'max level of vertical links',
    'MGC': 'merge chains',
    'MDC': 'middle of chain',
    'EXN': 'exit node',
    'HDC': 'head of chain'
}
